config/routes.rb
Rails.application.routes.draw do
  
  resources :characteristics

  resources :attributes

  resources :suggestbuylists

  resources :priorities

  resources :orders

  resources :reasons

  resources :stocks

  resources :users

  resources :products

  resources :categories

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
	has_and_belongs_to_many :products
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1
  # PATCH/PUT /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic.destroy
    respond_to do |format|
      format.html { redirect_to characteristics_url, notice: 'Characteristic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def characteristic_params
      params.require(:characteristic).permit(:name)
    end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.erb
<%= form_for(@characteristic) do |f| %>
  <% if @characteristic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@characteristic.errors.count, "error") %> prohibited this characteristic from being saved:</h2>

      <ul>
      <% @characteristic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<h1>Editing characteristic</h1>

<%= render 'form' %>

<%= link_to 'Show', @characteristic %> |
<%= link_to 'Back', characteristics_path %>

app/views/characteristics/index.html.erb
<h1>Listing characteristics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characteristics.each do |characteristic| %>
      <tr>
        <td><%= characteristic.name %></td>
        <td><%= link_to 'Show', characteristic %></td>
        <td><%= link_to 'Edit', edit_characteristic_path(characteristic) %></td>
        <td><%= link_to 'Destroy', characteristic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Characteristic', new_characteristic_path %>

app/views/characteristics/new.html.erb
<h1>New characteristic</h1>

<%= render 'form' %>

<%= link_to 'Back', characteristics_path %>

app/views/characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @characteristic.name %>
</p>

<%= link_to 'Edit', edit_characteristic_path(@characteristic) %> |
<%= link_to 'Back', characteristics_path %>